M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Tue 30 Aug 2022 10:44:57 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-30T22:44:57-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X2.8346Y-3.4646
X2.8346Y-4.4094
X5.0394Y-3.4646
X5.0394Y-4.4094
T2
X3.4961Y-4.1024
T0
M30
