M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Tue 30 Aug 2022 09:57:39 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-30T21:57:39-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
%
G90
G05
T1
X3.2299Y-2.5319
X3.2299Y-4.4614
X5.513Y-4.461
X5.5134Y-2.5327
T0
M30
